language: go
go:
- 1.11.x
env:
- GO111MODULE=on
script:
- make build
before_install:
- openssl aes-256-cbc -K $encrypted_f7374039b671_key -iv $encrypted_f7374039b671_iv
  -in deploy_key.enc -out ./deploy_key -d
