language: go
go:
- 1.11.x
env:
- GO111MODULE=on
jobs:
  include:
    - stage: build
      script: make build
    - stage: test
      env:
        global:
          - secure: "VxcTE6b/XUFcLqJCfhPgL+wurPOAQ86q4mWcjxP0uN42ct4Orlx9DseN4GY9yk4MNgORoaIn3hDL2IYmNkTybeL7kgMVmIvpZKLUKLddJOfKlmZLr7YjmN/rYnPkxDHD+kzIyQ28Bf28y1jn1uGrurWsZFJB3dZKXvIKYorD0/Umr63p77mdDobKS99ubmr2sFB221iBuJiRCRsciXrlltuGYFEssxq6jYKlqrQByMFOUVtHHJcTpy4O2l10AMkKMJlGojnlEmLV3O2bjE/Bb9YH7sp7DiUV7amzoySWcVSHUVFi3tBr3np8L4MLDsGBocC3pVfL7m7+pPRMywtBE79FSWV0pssWcsrBTqVhaSQDQcsf6CPlcZ9gPy3SKwkDQhANOfioEfkLrAG3Qol10Y4NUyA5XPqWU2XsA0DddWwCMjmPSkxV8GUpsg3rgZCTOUxOQchisXjnfjeRqbNnz987dRyb68Dh3CguBpgbQtBWDC7MUAR0VsKtkvNLO0Ef/lGbVpig6d4EbhMNO0YOpYZCpANdTiaYOjMWXkp92JWKUUfnGzDRVO1PH5JwxvMjEbhjYmnKSG8AFrqMN0wCVbUgmQT6VrXF/xCTgDbmhAXv3lk0ekzYo4XaOEDQD47DLWtC2rmjwq88/hNMG4qb0BW4U6gBx7EQid/3tPNxMKI="
      script: 
        - go get golang.org/x/tools/cmd/cover
        - go get github.com/mattn/goveralls
        - go test -v ./... -covermode=count -coverprofile=coverage.out
        - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
    # This is commented out as the api is currently deployed onto a self hosted
    # bare metal k8s cluster.  If that changes, CD can be reactivated.
    # - stage: deploy
    #   if: branch = master
    #   before_install:
    #     - openssl aes-256-cbc -K $encrypted_f7374039b671_key -iv $encrypted_f7374039b671_iv
    #       -in deploy_key.enc -out ./deploy_key -d
    #   script:
    #     - eval "$(ssh-agent -s)"
    #     - chmod 600 ./deploy_key
    #     - echo -e "Host $HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    #     - ssh-add ./deploy_key
    #     - ssh -p 73 -i ./deploy_key $DEPLOY_USER@$HOST "cd $REPO_DIR; git pull; bash ./kubernetes/deploynewimage.sh;"

