apiVersion: apps/v1
kind: Deployment
metadata:
  name: bouldertracker
  labels:
    app: bouldertracker-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bouldertracker-api
  template:
    metadata:
      labels:
        app: bouldertracker-api
    spec:
      containers:
      - name: bouldertracker-api
        image: tpageforfunzies/boulderlinux:armhf
        ports:
        - containerPort: 80
