apiVersion: v1
kind: Service
metadata:
  name: bouldertracker
  labels:
    app: bouldertracker-api
spec:
  type: NodePort
  selector:
    app: bouldertracker-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 31111